package com.hiresphere.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * AiAnalysis - Stores intelligent screening, semantic fit, and gap analysis
 * generated by the autonomous Gemini AI agent for a candidate against a job posting.
 */
public class AiAnalysis {

    private int id;
    private int candidateId;
    private int jobId;
    private int score; // 0 - 100
    private String matchVerdict; // "EXCELLENT_FIT", "GOOD_FIT", "POTENTIAL_MATCH", "LOW_MATCH"
    private List<String> strengths = new ArrayList<>();
    private List<String> skillGaps = new ArrayList<>();
    private String reasoning;
    private String recommendedAction;
    private List<String> suggestedInterviewQuestions = new ArrayList<>();
    private LocalDateTime createdAt = LocalDateTime.now();

    public AiAnalysis() {
        this.createdAt = LocalDateTime.now();
    }

    public AiAnalysis(int candidateId, int jobId, int score, String matchVerdict, String reasoning) {
        this.candidateId = candidateId;
        this.jobId = jobId;
        this.score = score;
        this.matchVerdict = matchVerdict;
        this.reasoning = reasoning;
        this.createdAt = LocalDateTime.now();
    }

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getCandidateId() { return candidateId; }
    public void setCandidateId(int candidateId) { this.candidateId = candidateId; }

    public int getJobId() { return jobId; }
    public void setJobId(int jobId) { this.jobId = jobId; }

    public int getScore() { return score; }
    public void setScore(int score) { this.score = score; }

    public String getMatchVerdict() { return matchVerdict; }
    public void setMatchVerdict(String matchVerdict) { this.matchVerdict = matchVerdict; }

    public List<String> getStrengths() { return strengths; }
    public void setStrengths(List<String> strengths) { this.strengths = strengths; }

    public List<String> getSkillGaps() { return skillGaps; }
    public void setSkillGaps(List<String> skillGaps) { this.skillGaps = skillGaps; }

    public String getReasoning() { return reasoning; }
    public void setReasoning(String reasoning) { this.reasoning = reasoning; }

    public String getRecommendedAction() { return recommendedAction; }
    public void setRecommendedAction(String recommendedAction) { this.recommendedAction = recommendedAction; }

    public List<String> getSuggestedInterviewQuestions() { return suggestedInterviewQuestions; }
    public void setSuggestedInterviewQuestions(List<String> suggestedInterviewQuestions) {
        this.suggestedInterviewQuestions = suggestedInterviewQuestions;
    }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
